Develop
p4kl0nc4t/kyros pull request #21
Opened 2022-01-15 08:21 UTC by reinier-millo

I have rebased master branch into develop, and added support to prevent websocket be closed after 30 seconds. It must solve issue #18

2022-01-15 19:27 UTC, p4kl0nc4t requested changes
At a glance, it looks quite good to me. However, you need to make sure that your code is consistent with the whole code base (make sure it complies to PEP8).

I haven't tested the code though, but it looks promising.

2022-01-15 19:27 UTC, lc-at commented on kyros/websocket.py
> +    async def keepAlive(self):
I think that the function name should comply to the PEP-8 standard. There should be docstrings too, I guess.

2022-01-15 19:27 UTC, lc-at commented on kyros/websocket.py
> +            constants.WEBSOCKET_URI, origin=constants.WEBSOCKET_ORIGIN, close_timeout = None,ping_interval = None)
The comma needs an extra space.

2022-01-15 19:28 UTC, p4kl0nc4t commented
@rijumone, can you test and review this?

2022-01-15 22:41 UTC, reinier-millo commented on kyros/websocket.py
> +    async def keepAlive(self):
Sorry, it's my mistake, i have moved out solution from a project code that i'm working. I have uploaded the fix.

2022-01-15 22:41 UTC, reinier-millo commented on kyros/websocket.py
> +            constants.WEBSOCKET_URI, origin=constants.WEBSOCKET_ORIGIN, close_timeout = None,ping_interval = None)
Fixed

2022-01-16 19:22 UTC, rijumone commented
> @rijumone, can you test and review this?

@p4kl0nc4t, I would love to. However, I am yet to get this library running on my dev environment owing to #19 . Would it be possible to hop on a Zoom call or something to get me up to speed on this? An overall walk-through of the library would also be greatly appreciated.

2022-01-30 03:49 UTC, merged